### ISSUE TITLE
Create new self-hosted runner using Docker

### ISSUE THREAD

**Issue by dmpinder** [vatu-team/workflows#2]
1. Create a new runner called `NYC-R1`
2. Use Docker to install required dependencies
3. Replace with existing runner once working
4. Write up docs on Runner creation
5. Update all build processes to remove dependencies from config files

**Comment by aktech** [comment]
2 cents on self-hosting runners:

I built a service for running self-hosted GitHub Action runners on cloud with 0 maintenance and free for open source: https://cirun.io/

It's on-demand, which means you only pay to your cloud provider for the time you're using it.
All you need is a simple configuration .cirun.yml file, here is a [demo](https://www.youtube.com/watch?v=lDx0YVTn6yg).
Also available on GitHub Marketplace as well: https://github.com/marketplace/cirun-io

**Comment by michaelbragg** [comment]
Is this task still required now we have NYC-R2 up and running?

Instructions link for later ref: [https://github.com/vatu-team/infrastructure-handbook/wiki/Servers#github-runner-server](https://github.com/vatu-team/infrastructure-handbook/wiki/Servers#github-runner-server)

**Comment by dmpinder** [comment]
I left it open in case we needed to refer back, as I haven't installed Docker on it. But considering everything is working currently, I'll close it.
