### ISSUE TITLE
Dependabot Auto Deploy Workflow

### ISSUE THREAD

**Issue by michaelbragg** [vatu-team/workflows#32]

**Comment by dmpinder** [comment]
Can we close this issue now @michaelbragg ?

**Comment by michaelbragg** [comment]
We're still getting some failed merges:

> Canceling since a higher priority waiting request for 'Dependabot Auto Merge--main' exists

Examples:
- https://github.com/vatu-team/awani/actions/runs/3636414928
- https://github.com/vatu-team/thebraintumourcharity/actions/runs/3636082399

Concurrency values:
  
  ```yml
  concurrency:
  group: ${{ github.workflow }}--${{ github.ref_name || github.head_ref }}
  cancel-in-progress: true
  ```
  
  - `github.ref_name`: The short ref name of the branch or tag that triggered the workflow run. This value matches the branch or tag name shown on GitHub. For example, `feature-branch-1`.
  - `github.head_ref`: The `head_ref` or source branch of the pull request in a workflow run. This property is only available when the event that triggers a workflow run is either `pull_request` or `pull_request_target`.
  
As Auto Merge Workflow is called after a previous workflow. GitHub does not pass through the `pull_request` details to this secondary workflow 😞.

So it is falling back to `Dependabot Auto Merge--main` which would be the same as any branch being merged into the `main` branch.
  
 The fix is to get this concurrency setting right.

**Comment by michaelbragg** [comment]
Actually, would it be better to remove the "cancel-in-progress" option.

Going to try this.

**Comment by michaelbragg** [comment]
https://github.com/vatu-team/workflows/wiki/002-Dependabot

**Comment by michaelbragg** [comment]
I've updated the TBTC and Awani repositories to trial the number code. If this works this task is completed.
Will release a v1.0.0 of the Workflows and update all the projects to use it.
