### ISSUE TITLE
PHP Code Sniffer

### ISSUE THREAD

**Issue by dmpinder** [vatu-team/workflows#8]
The aim of this workflow is to lint the project code and flag any code that doesn't adhere to the project standards (phpcs.xml.dist).

Workflow must:
1. Be project agnostic and take all standards, paths, and config from the projects Composer config file
2. Install PHP Code Sniffer from the tools/phpcs directory using Composer
3. Comand run composer script composer run-script test-phpcs
4. Have a sematic version set in the file header coments

Examples: 
https://github.com/vatu-team/thebraintumourcharity/blob/main/.github/workflows/static-analysis.yml#L19-L73
https://github.com/vatu-team/demo.vatu.dev/blob/main/.github/workflows/static-analysis.yml#L17-L69

**Comment by michaelbragg** [comment]
https://github.com/vatu-team/demo.vatu.dev/blob/main/.github/workflows/static-analysis.yml#L56-L57

Runs `composer run test-phpcs` from instructions in a remote file.

Next step is to convert the full workflow.

**Comment by michaelbragg** [comment]
Added a reusable workflow for PHP CodeSniffer.
Example use: https://github.com/vatu-team/test-workflows/blob/b7769d2a9a98034661fa5366a15a81f60be5abda/.github/workflows/static-analysis.yml#L23-L29

Notes:
- Workflow needs to live inside `.github/workflows` to be called by another workflow. _Hopefully we can move this outside the directory in the future._
